objects=\
ba_create_quaternion_from_rotation_matrix_0.o\
ba_create_quaternion_from_rotation_matrix_1.o\
ba_create_quaternion_from_rotation_matrix.o\
ba_create_rodrigues_param_from_rotation_matrix.o\
ba_create_rotation_matrix_rodrigues.o\
ba_evaluate.o\
ba_evaluate_grad_camera.o\
ba_evaluate_grad_point.o\
ba_lbfgs.o\
ba_lbfgs_main.o\
ba_project_point.o\
ba_reprojection_error.o\
ba_rodrigues_rotation_derivatives.o\
compute_1st_camera_matrix.o\
compute_2nd_camera_matrix_from_essential_matrix.o\
compute_2nd_camera_matrix_from_essential_matrix_horn.o\
compute_2nd_camera_matrix_from_fundamental_matrix.o\
compute_3dpoint_depth.o\
compute_3dpoints.o\
compute_essential_matrix.o\
compute_givens_rotation_matrix.o\
compute_linear_triangulation.o\
compute_linear_triangulation_two_cameras.o\
compute_quaternion_from_rotation.o\
compute_rotation_from_quaternion.o\
compute_RQ_decomposition.o\
convert_features_and_descriptors_to_sfm.o\
decompose_camera_matrix.o\
epnp_choose_control_points.o\
epnp_compute_A_and_b_gauss_newton.o\
epnp_compute_barycentric_coordinates.o\
epnp_compute_ccs.o\
epnp_compute_L_6x10.o\
epnp_compute_pcs.o\
epnp_compute_pose.o\
epnp_compute_R_and_t.o\
epnp_compute_rho.o\
epnp_copy_R_and_t.o\
epnp_dist2.o\
epnp_dot.o\
epnp_estimate_R_and_t.o\
epnp_fill_M.o\
epnp_find_betas_approx_1.o\
epnp_find_betas_approx_2.o\
epnp_find_betas_approx_3.o\
epnp_gauss_newton.o\
epnp_normal_equations_solve.o\
epnp_qr_solve.o\
epnp_reprojection_error.o\
epnp_solve_for_sign.o\
free_features_and_descriptors.o\
normalize_coordinates.o\
select_correct_2nd_camera_matrix.o\
sfm10_error_handler.o\
sfm_add_camera.o\
sfm_add_camera_imagepoints.o\
sfm_add_camera_matrix.o\
sfm_add_imagepoint_to_threedpoint.o\
sfm_check_initial_camera_pair.o\
sfm_check_threedpoints.o\
sfm_common.o\
sfm_compute_added_camera_matrix_b.o\
sfm_compute_added_camera_matrix.o\
sfm_compute_added_camera_matrix_exterior_orientation.o\
sfm_compute_average_separation_angle.o\
sfm_compute_camera_matrix_main.o\
sfm_compute_camera_matrix.o\
sfm_compute_exterior_orientation_main.o\
sfm_compute_features_main.o\
sfm_compute_focal_length.o\
sfm_compute_focal_length_main.o\
sfm_compute_C_from_R_t.o\
sfm_compute_good_matches.o\
sfm_compute_good_matches_main.o\
sfm_compute_match.o\
sfm_compute_matches.o\
sfm_compute_matches_main.o\
sfm_compute_P_from_K_R_t.o\
sfm_compute_relative_camera_pose.o\
sfm_compute_threedpoints.o\
sfm_free_features_and_descriptors.o\
sfm_free_threedpoints.o\
sfm_get_camera_matrix.o\
sfm_get_camera_matrix_ind.o\
sfm_get_camera_threedpoints_imagepoints.o\
sfm_get_next_camera_2.o\
sfm_get_next_camera.o\
sfm_get_threedpoints_nbr.o\
sfm_lbfgs_bundle_adjustment.o\
sfm_match_distance_squared.o\
sfm_merge_duplicate_features.o\
sfm_merge_threedpoints.o\
sfm_normalize_2dpoints.o\
sfm_normalize_3dpoints.o\
sfm_optimize_camera_matrix.o\
sfm_optimize_camera_matrix_jacobian.o\
sfm_optimize_camera_matrix_residual.o\
sfm_pba_bundle_adjustment.o\
sfm_print_depth_range_threedpoints.o\
sfm_print_F.o\
sfm_print_features_and_descriptors.o\
sfm_print_matches.o\
sfm_print_P.o\
sfm_print_reprojection_error_threedpoints.o\
sfm_print_threedpoints.o\
sfm_print_threedpoints_gif_b.o\
sfm_print_threedpoints_gif.o\
sfm_print_threedpoints_in.o\
sfm_print_threedpoints_nvm.o\
sfm_print_threedpoints_ply.o\
sfm_read_F.o\
sfm_read_features_and_descriptors.o\
sfm_read_image_filenames.o\
sfm_read_matches.o\
sfm_read_P.o\
sfm_read_threedpoints.o\
sfm_recompute_threedpoint_b.o\
sfm_recompute_threedpoint.o\
sfm_recompute_threedpoints_b.o\
sfm_recompute_threedpoints.o\
sfm_reconstruct_3d_from_2cameras.o\
sfm_remove_spurious_matches_2.o\
sfm_remove_spurious_matches_3.o\
sfm_remove_spurious_matches_4.o\
sfm_remove_spurious_matches.o\
sfm_remove_spurious_threedpoints.o\
sfm_reprojection_error_threedpoint.o\
sfm_reprojection_error_threedpoints.o\
sfm_separation_angle_threedpoint.o\
sfm_separation_angle_threedpoints.o\
sfm_update_camera_matrix.o
